[package]
name = "cadder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cadder-daemon = { version = "0.8.0", path = "../cadder-daemon" }
cadder-operator = { version = "0.8.0", path = "../cadder-operator" }
cadder-protocol = { version = "0.8.0", path = "../cadder-protocol" }
clap = { version = "4.6.1", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.2"
tokio = { version = "=1.52.3", features = ["rt"] }
tui-term = "0.3.4"
